app:
  zooplus:
    cli:
      textArt: true
    anagram:
      searcher:
        type: "sorted"
    resources:
      dictionary:
        dictionaryDirPath: "dictionary"
        sortedDictionaryPath: "sorted/sorted.txt"